### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Hotshoot911** [riQQ/Hearth-Arena-Uploader#5]
I followed all the steps and cant get it to export. Was there an update on HearthArenas end that stopped this from working?

**Comment by Confirm4Crit** [comment]
Came to ask the same thing. It was working about a week ago, can't get it to do anything now. I'm going to try to reinstall the plugin, see if that helps.

**Comment by riQQ** [comment]
Fixed in new release: https://github.com/riQQ/Hearth-Arena-Uploader/releases/tag/0.1.3.
